name: Core
version: '${project.version}'
main: net.fabledrealms.Core
api-version: 1.20
authors: [joshscoper,KacperM,Relism,acsn1]
description: The core plugin for FabledRealms
website: www.fabledrealms.net
commands:
  economy:
    aliases:
      - eco
    description: The economy module root command
    usage: /economy
  graveyard:
    aliases:
      - gy
      - graves
    description: The graveyard module root command.
    usage: /graveyard
  quests:
    aliases:
      - quest
    description: The quest module root command.
  shopadmin:
    aliases:
      - adminshop
    description: The shop management module root command.
  lootchest:
    aliases: lc
    description: The lootchest module root command.