name: Core
version: '${project.version}'
main: net.fabledrealms.Core
api-version: 1.20
authors: [joshscoper]
description: The core plugin for FabledRealms
website: www.fabledrealms.net
commands:
  graveyard:
    aliases:
      - gy
      - graves
    description: The graveyard module root command.
    usage: /graveyard